---
title: "Reports Methodology"
author: "Rob R"
date: "Friday, April 17, 2015"
output: word_document
---

##Programming Methodology for KHIIS Reports

### SQL

####Keys, Constraints, and Utility Functions:
The "Raw Report Tables" file has been left intact for testing purposes. Use the modular form in production, notably field ordering for gallbladder procedure tables differ between the two versions, and down-stream processing relies on the newer ordering within Modular_Report_Call.

In all cases, the derived primary key (UniqID) is a concatenation of the following fields: MembershipID, PatientDOB, PatientGenderCode, and FamilyMembershipID.

Selections were constrained by ensuring Member, Summary, and Detail fields: Eligibility End Date, Last Date of Service, and Service Date respectively were within the yearly date range. E.g. 2010-01-01 to 2010-12-31.

All uknown genders (PatientGenderCode=U) were removed.

####Utility Functions:

* ElgMoMid: Takes the Member record's Eligibility Start Date, End Date, Submission Quarter, and the given year's date. 
 Tests for date reversal (start > end) and fixes if needed. Returns a count of months covered in the quarter. (Covered is defined as having coverage as of the 15th of the month.)
 
* age_band: Takes Date of Birth (PatientDOB), and Year Start Date.
Calculates age as of January 1 of given year and returns age-band assignment of 0-18, 19-64, and 65+.

* elg_band: Takes a sum of covered months and returns the eligibility band. 

 Count Months | Band
--------------|------
Months < 1    | 0
Months < 4    | 1-3
Months < 7    | 4-6
Months < 10   | 7-9
Months < 12   | 10-12
Months > 12   | 10-12


####Temporary Table Generation ReportProc(Year_Start='YYYYMMDD',Year_End='YYYYMMDD'):
Temporary table generation is in a stored procedure (ReportProc) accepting date bounds (year start, and year end).

1. Table dentoptclaims: Created in order to later remove dental and vision claims since not all plans provide such coverage. Derived from Detail file, and filtered on Provider Specialty and Taxonomy codes. See Appendix A (pg 230) and Appendix C (Pgs 249,252-3) of the Data Dictionary. (4th Ed.)

2. Table adjclaims: Created in order to later remove any claims with positive or negative adjustments. Derived from Detail file, selecting all records with ClaimAction adjustments NA and PA.
  
3. Table tempyearlytable: An intermediate table to subset Summary Claims to be within year bounds and excludes supplementary and ancillary plans based on Plan Type and Product Type fields. (PlnTyp!=5,6 and PrdTyp=1).

4. Table yearlytable: Uses intermediate table above and appends binary diagnosis indicators for Diabetes, CHF, COPD, and Asthma.
E.g.  
````IF((PrimaryDiagnosis REGEXP '^250.*')|(SecondaryDiagnosis REGEXP '^250.*')|(ThirdDiagnosis REGEXP '^250.*'),1,0) as 'diab'
````
Also LEFT JOINs on dentoptclaims and returns only records not found with dental and vision claims.

5. Table tempmemb: An intermediate table subsetting the Member file to be within year bounds. Also calls age_band and ElgMoMid functions to calculate member age and coverage based on quarter. Joins Member Zipcode (Truncated at 5 digits) with Zipcode table to return County. 

6. Table memb_summ: Table summarizing the tempmemb table to get a total sum of months per member, and filter by state, plan and product type.

7. Table claim_summ: Table summarizes previous yearly table. E.g. calls MAX(diab), and SUM(TotalCharges) with GROUP BY uniqID to get a single member record with diagnosis variables and an aggregate charges over the year. The yearlytable is LEFT JOINed with the adjusted claims table (adjclaims) on uniqID and either Claim Number or if Detail Service Date is within Summary's First and Last Date of Service. Claims matched in the adjclaims table are removed.

8. Temporary tables for specific procedures -- Hip Replacement, Colonoscopy etc. are then created based on CPT procedure codes in the Detail file. Only Major Med Plans are included. (PlnTyp!=5,6 and PrdTyp=1).

####Aggregated Outputs - Modular_Report_Call:
1. *Year* Raw Members: Gives uniqID, Age Band, Patient Gender, County, Months Eligibility Band, Months Eligible, and submission year.

2. *Year* Raw Claims: Combines summarized claims information (e.g yearly total of AllowedCharges) and county and eligibility band information from the Member records.

3. *Year* *Procedure* Claims: Procedure level claim summaries are created by combining the previously created procedure tables with subset Summary table yearlytable. Summary claims are selected by claim or date range and then grouped by uniqID and summed to get a total incident cost-of-care measure. 


### R

####Libraries:
data.table, lubridate, dplyr, stringr, assertthat, reshape2.

####Definition:
In our calculations Average Total Cost is defined as the sum of total paid charges and member responsiblity for all members of the group divided by the sum of group member months divided by twelve or for each group SUM(TotPd+Mbrsp)/(SUM(MembMo)/12). If the sum of member months was 0, the square root of the group size was used instead or SUM(TotPd+Mbrsp)/sqrt(Group Size).

####Utility and Helper Functions:
All reading functions have a hard-coded base path and file name suffix. E.g.
````
base_path = 'D:/MySQL_KHIIS_OUT/'
file_name_suffix = '_Raw_Members.csv'
````

Source: readData.r
Functions:

 * readMembersData(Year) - Read in members data, set header/column names appropriately.
 * readClaimsData(Year) - Read in claims data, set header/column names, create "TotCost" variable which is the sum of Total Allowed Charges and Member Responsibility.
 * readProcedureData(Year,Procedure) - Read in Procedure data, set names, create "TotCost" variable. Procedure must be one of: Hip,Gall,Mammo or Colo.
 
Soure: PopEst.R  
Functions: Reads in and calculates adjusted population for each county based on yearly estimated population - general quarters population. See file for details on census file used.
 
#### Final Report Generation:

1. Membership Analysis  
Source: Membership_Analysis.R   
Reads member data and creates counts and summaries based on grouping by age band, eligibility band, county, gender, and year. Fills any missing variable combinations with 0's and writes to disk. Also creates Completeness estimates by calculating percent of estimated county population that is found within KHIIS member file. Assigns to quartiles C1 - C4 and writes to disk. 


2.Total Cost of Care  
Source: Tot_Cost_Care.R  
Creates full data frame of claims data for all years. Groups data by gender, county, age band, eligibiity band, and year.
For each group, calculates median TotCost and average TotCost. Any missing group combination is created and filled with 0s.
The table is written to disk. Subsequent variations omit certain groups in order to derive other tables -- e.g. median cost of care in a county and year without splitting by gender.

3. Diagnosis Cost of Care  
Source: Diagnosis_Cost_Care.R, Diagnosis_gndrVars_Cost_Care.R  
Follows the same pattern as Total Cost of Care with groupings on Disease binary variables. Calculates median and average cost of care with disease groupings. The gendered version is not currently used as it identifies individuals too specifically.

4. Procedure Cost of care  
Source: Procedure_Cost.R  
Follows Total Cost of Care pattern reading in procedure based tables and returning median and mean cost of care for various groupings.
