## Run All
rm(list = setdiff(ls(), lsf.str()))
source("Diagnosis_Cost_Care.R")
rm(list = setdiff(ls(), lsf.str()))
source("Diagnosis_gndrVars_Cost_Care.R")
rm(list = setdiff(ls(), lsf.str()))
source("Membership_Analysis.R")
rm(list = setdiff(ls(), lsf.str()))
source("PopEst.R")
rm(list = setdiff(ls(), lsf.str()))
source("Procedure_Cost.R")
rm(list = setdiff(ls(), lsf.str()))
source("readData.R")
rm(list = setdiff(ls(), lsf.str()))
source("Tot_Cost_Care.R")
rm(list = setdiff(ls(), lsf.str()))